spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git仓库  配置仓库应该独立 与代码仓库分开
          uri: https://gitee.com/xiaochuang2019/springcloud-demo.git
          search-paths:
            - configfiles
            - #默认拉取的分支
           default-label: master
      #从哪个分支去拉去配置文件
      label: test
server:
  port: 8888